name: Library Actions

on:
    push:
        # paths:
        #     - librarybookingsystem/library.py
        branches:
            - main

jobs:
    test_code: #name of job
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.12"
                  cache: "pip"
            - name: Install dependencies
              run: python -m pip install --upgrade pip
            - name: Run tests
              working-directory: librarybookingsystem
              run:
                  pwd
                  pytest tests/test_library.py
